load data and setup

In [ ]:
from pymongo import MongoClient
import pandas as pd

# read only
connection_string = "mongodb+srv://thomas:4c84qHaDIZWgpMf3@cluster0.xa1cxxl.mongodb.net/APP"

# Connect to MongoDB
client = MongoClient(connection_string)

# Access database
db = client['APP']

collection = db['stocks']

df = pd.DataFrame(list(collection.find({}, {'_id': 0})))
df['timestamp'] = pd.to_datetime(df['timestamp'])

Earnings data

In [10]:
earnings_df=df[df['info'].str.startswith('e{')]

In [11]:
earnings_df

,Stock,Rank,EPS Percentage,Growth,Last_Price,Date,Time,info,timestamp,Sector
88,ccep,2-Buy,0,4.05,90.44,6/6/25,Unknown,"e{""symbol"":""CCEP"",""name"":""Coca-Cola Europacifi...",2025-06-03 15:07:33.383,NA
89,kt,4-Sell,0,47.15,18.8,6/6/25,Unknown,"e{""symbol"":""KT"",""name"":""KT Corporation"",""time""...",2025-06-03 15:07:33.990,NA
90,sbsw,There is no info on this stock,There is no info on this stock,There is no info on this stock,6.23,6/6/25,Unknown,"e{""symbol"":""SBSW"",""name"":""Sibanye Stillwater L...",2025-06-03 15:07:34.486,NA
91,cmcm,There is no info on this stock,There is no info on this stock,There is no info on this stock,4.38,6/6/25,Unknown,"e{""symbol"":""CMCM"",""name"":""Cheetah Mobile Inc.""...",2025-06-03 15:07:34.791,NA
92,abm,2-Buy,0,5.17,52.69,6/6/25,Before Market Open,"e{""symbol"":""ABM"",""name"":""ABM Industries Incorp...",2025-06-03 15:07:35.484,NA
...,...,...,...,...,...,...,...,...,...,...
117119,smsi,3-Hold,0,0,0.68,5/6/26,Unknown,"e{""symbol"":""SMSI"",""name"":""Smith Micro Software...",2026-03-06 10:02:17.556,Computer and Technology
117120,cyn,There is no info on this stock,There is no info on this stock,There is no info on this stock,1.49,3/4/26,Unknown,"e{""symbol"":""CYN"",""name"":""Cyngn Inc."",""epsForec...",2026-03-06 10:02:18.256,N/A
117121,clrb,4-Sell,0,0,2.77,5/12/26,Unknown,"e{""symbol"":""CLRB"",""name"":""Cellectar Bioscience...",2026-03-06 10:02:19.249,Medical
117122,hyfm,There is no info on this stock,There is no info on this stock,There is no info on this stock,1.07,3/4/26,Unknown,"e{""symbol"":""HYFM"",""name"":""Hydrofarm Holdings G...",2026-03-06 10:02:19.953,N/A
117123,auud,There is no info on this stock,There is no info on this stock,There is no info on this stock,0.77,3/4/26,Unknown,"e{""symbol"":""AUUD"",""name"":""Auddia Inc."",""epsFor...",2026-03-06 10:02:20.957,N/A

past earnings example ie stock has already posted earnings, and we track result: symbol, name, epsForecast(what they were expected to have), eps(actual eps), noof ests (number of estimates), market cap, surprise (surprise percentage of earnings), is past earnings: true if earnings has passed, false otherwise, correct date: date of actual earnings

In [12]:
earnings_df.iloc[-1]['info']

'e{"symbol":"AUUD","name":"Auddia Inc.","epsForecast":"N/A","eps":"$14.97","noOfEsts":"1","marketCap":"$2,291,331","surprise":"N/A","isPastEarnings":true,"correct_date":"2026-03-04"}'

example of future earnings example, now u have time (before market, after or unknown, last year eps) and is past earnings false.

In [13]:
earnings_df.iloc[0]['info']

'e{"symbol":"CCEP","name":"Coca-Cola Europacific Partners plc","time":"N/A","lastYearEPS":"N/A","epsForecast":"N/A","noOfEsts":"4","marketCap":"$42,048,841,553","isPastEarnings":false}'

Et is where people just check earnings time (date and time). Timestamp is when they did it (as it is in all dfs)

In [16]:
earnings_time_df=df[df['info'].str.startswith('et')]

In [17]:
earnings_time_df

,Stock,Rank,EPS Percentage,Growth,Last_Price,Date,Time,info,timestamp,Sector
0,ggrg,There is no info on this stock,There is no info on this stock,There is no info on this stock,There is no info on this stock,N/A,N/A,et,2025-06-03 15:05:27.784,NA
1,eix,3-Hold,-6.64,7.01,55.5,7/24/25,Unknown,et,2025-06-03 15:05:28.987,NA
2,urng,There is no info on this stock,There is no info on this stock,There is no info on this stock,There is no info on this stock,N/A,N/A,et,2025-06-03 15:05:29.984,NA
3,etd,3-Hold,0,0,26.15,7/30/25,Unknown,et,2025-06-03 15:05:30.782,NA
4,rnw,2-Buy,0,0,6.82,6/4/25,Unknown,et,2025-06-03 15:05:31.587,NA
...,...,...,...,...,...,...,...,...,...,...
117176,bah,3-Hold,-1.94,2.81,79.8,5/22/26,Unknown,et,2026-03-06 10:03:34.458,Business Services
117177,phsp,There is no info on this stock,There is no info on this stock,There is no info on this stock,There is no info on this stock,N/A,N/A,et,2026-03-06 10:03:36.156,N/A
117178,niq,2-Buy,17.18,0,13.2,5/22/26,Unknown,et,2026-03-06 10:03:37.556,Business Services
117179,mdb,3-Hold,-0.15,11.66,263.93,6/3/26,Unknown,et,2026-03-06 10:03:38.553,Computer and Technology
117180,expi,3-Hold,0,0,6.78,5/5/26,Unknown,et,2026-03-06 10:03:39.561,Finance

My monthly yt videos are based on this, every month for over 6k stocks, record rank and price when looked up (last price), info contains 52 week high and low

In [18]:
earnings_price_df=df[df['info'].str.startswith('el')]

In [19]:
earnings_price_df

,Stock,Rank,EPS Percentage,Growth,Last_Price,Date,Time,info,timestamp,Sector
3128,v,3,-3.4,13.1,349.82,7/22/25,Unknown,"el{""high"":375.51,""low"":252.7}",2025-06-13 19:41:52.339,NA
3129,val,5-Sell,0.0,0,46.01,7/30/25,Unknown,"el{""high"":84.2,""low"":27.15}",2025-06-13 19:41:57.374,NA
3130,vale,3,0.0,17.51,9.4,7/24/25,Unknown,"el{""high"":12.05,""low"":8.06}",2025-06-13 19:41:58.356,NA
3131,vbnk,5-Sell,0.0,0,11.01,9/4/25,Unknown,"el{""high"":18.38,""low"":8.51}",2025-06-13 19:42:07.923,NA
3132,vbtx,3,0.0,0,24.5,7/22/25,Unknown,"el{""high"":31.62,""low"":19.27}",2025-06-13 19:42:08.770,NA
...,...,...,...,...,...,...,...,...,...,...
107534,azta,4,0.0,0,28.62,5/6/26,Unknown,"el{""high"":47.55,""low"":23.91}",2026-02-14 15:26:54.894,Medical
107535,abnb,2,9.89,13.68,121.35,5/7/26,Unknown,"el{""high"":163.93,""low"":99.88}",2026-02-14 15:27:03.342,Consumer Discretionary
107536,alsmy,3,0,0,3.37,NA,Unknown,"el{""high"":3.51,""low"":1.8}",2026-02-14 15:27:04.863,Transportation
107537,amat,2,15.28,11.7,354.91,5/21/26,Unknown,"el{""high"":376.32,""low"":123.9}",2026-02-14 15:27:05.276,Computer and Technology
107538,asccy,5,0,0,29.08,2/13/26,Unknown,"el{""high"":29.7,""low"":17.75}",2026-02-14 15:27:10.027,Consumer Discretionary

This one is for people checking the zachs rank only for their stocks at time timestamp

In [20]:
portfolio_df=df[df['info'].str.startswith('p')]

In [21]:
portfolio_df

,Stock,Rank,EPS Percentage,Growth,Last_Price,Date,Time,info,timestamp,Sector
44,ggrg,There is no info on this stock,There is no info on this stock,There is no info on this stock,There is no info on this stock,N/A,N/A,p,2025-06-03 15:06:40.388,NA
45,eix,3-Hold,-6.64,7.01,55.5,7/24/25,Unknown,p,2025-06-03 15:06:40.787,NA
46,urng,There is no info on this stock,There is no info on this stock,There is no info on this stock,There is no info on this stock,N/A,N/A,p,2025-06-03 15:06:41.576,NA
47,etd,3-Hold,0,0,26.15,7/30/25,Unknown,p,2025-06-03 15:06:42.082,NA
48,rnw,2-Buy,0,0,6.82,6/4/25,Unknown,p,2025-06-03 15:06:42.483,NA
...,...,...,...,...,...,...,...,...,...,...
117233,bah,3-Hold,-1.94,2.81,79.8,5/22/26,Unknown,p,2026-03-06 10:07:42.863,Business Services
117234,phsp,There is no info on this stock,There is no info on this stock,There is no info on this stock,There is no info on this stock,N/A,N/A,p,2026-03-06 10:07:44.161,N/A
117235,niq,2-Buy,17.18,0,13.2,5/22/26,Unknown,p,2026-03-06 10:07:44.853,Business Services
117236,mdb,3-Hold,-0.15,11.66,263.93,6/3/26,Unknown,p,2026-03-06 10:07:45.654,Computer and Technology
117237,expi,3-Hold,0,0,6.78,5/5/26,Unknown,p,2026-03-06 10:07:46.361,Finance

Dividend df

In [22]:
dividends_df=df[df['info'].str.startswith('d')]

In [23]:
dividends_df

,Stock,Rank,EPS Percentage,Growth,Last_Price,Date,Time,info,timestamp,Sector
111,amkr,5-Strong Sell,0,0,18.57,8/4/25,Unknown,"d{""Info"":""Amkor Technology, Inc. Common Stock""...",2025-06-03 15:08:42.685,NA
112,gogl,5-Strong Sell,0,0,7.57,8/27/25,Unknown,"d{""Info"":""Golden Ocean Group Limited Common St...",2025-06-03 15:08:43.383,NA
113,hwc,3-Hold,0,0,54.86,7/15/25,Unknown,"d{""Info"":""Hancock Whitney Corporation Common S...",2025-06-03 15:08:44.385,NA
114,lstr,4-Sell,0,0,139.43,7/29/25,Unknown,"d{""Info"":""Landstar System, Inc. Common Stock"",...",2025-06-03 15:08:44.982,NA
115,nrim,1-Strong Buy,0,0,90.3,7/23/25,Unknown,"d{""Info"":""Northrim BanCorp Inc Common Stock"",""...",2025-06-03 15:08:45.387,NA
...,...,...,...,...,...,...,...,...,...,...
117008,sbgi,2-Buy,0,0,15.51,5/6/26,Unknown,"d{""Info"":""Sinclair, Inc. Class A Common Stock""...",2026-03-06 09:57:26.456,Consumer Discretionary
117009,tcbs,There is no info on this stock,There is no info on this stock,There is no info on this stock,16.65,3/26/26,Unknown,"d{""Info"":""Texas Community Bancshares, Inc. Com...",2026-03-06 09:57:27.451,N/A
117010,umbf,1-Strong Buy,-2.57,11.62,117.46,5/5/26,Unknown,"d{""Info"":""UMB Financial Corporation Common Sto...",2026-03-06 09:57:29.366,Finance
117011,ubcp,There is no info on this stock,There is no info on this stock,There is no info on this stock,15.25,5/8/26,Unknown,"d{""Info"":""United Bancorp, Inc. Common Stock"",""...",2026-03-06 09:57:30.255,N/A
117012,vctr,3-Hold,0,14.15,71.1,5/14/26,Unknown,"d{""Info"":""Victory Capital Holdings, Inc. Class...",2026-03-06 09:57:31.354,Finance

Early entries have name, time (which is payment date), dic yield(in percentage for annualised div), and div amount for the ex date

In [26]:
dividends_df.iloc[0]['info']

'd{"Info":"Amkor Technology, Inc. Common Stock","Time":"6/25/2025","Yield":1.83,"Dividend_Amount":0.08269}'

Newer entries add ex date

In [27]:
dividends_df.iloc[-1]['info']

'd{"Info":"Victory Capital Holdings, Inc. Class A Common Stock","Time":"3/25/2026","Yield":2.76,"Dividend_Amount":0.49,"Ex_Date":"2026-03-10"}'